name: Update Guest Data
on:
  repository_dispatch:
    types: [update-guest-data]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update guest data
        run: |
          echo '${{ github.event.client_payload.guest_data }}' > data/current-booking.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/current-booking.json
          git commit -m "Update guest data" || exit 0
          git push
